### ISSUE TITLE
steamwebhelper doesn't respond

### ISSUE THREAD

**Issue by beboux9** [mnapoli/aoe2-de-macos#18]
<img width="701" alt="Capture d’écran 2024-11-16 à 13 46 31" src="https://github.com/user-attachments/assets/a97b2bff-35b0-4a6b-b088-d7620383ff14">

I tried launching steam the exact same way as every day and it's telling me that steamwebhelper doesn't respond. I've tried all the option to restart but nothing seems to work the same message always pops up. Can some help me figuring out why this started happening? :(

**Comment by Adri96** [comment]
I actually found a way around this one. It implies:
- downgrading steam in Crossover to a previous version
- Running it with explicit flags to prevent it from updating

In order to run the commands, you need to know how to open the terminal: 
https://support.codeweavers.com/en_US/miscellanous/run-a-windows-app-from-terminal

Then, navigate to Program Files (x86)/Steam in your terminal and execute these two commands:
- wine --cx-app steam.exe -forcesteamupdate -forcepackagedownload -overridepackageurl http://web.archive.org/web/20240520if_/media.steampowered.com/client -exitsteam
- wine --cx-app steam.exe -noverifyfiles -nobootstrapupdate -skipinitialbootstrap -norepairfiles -overridepackageurl

For now, I need to run these two commands every time I start steam in crossover, but it works! I’ve been playing without problems :) 

Let me know if you need further help!

PS: found the two arcane commands here: https://github.com/Whisky-App/Whisky/issues/1199
